import type { Metadata } from "next";
import { Geist, Geist_Mono, Just_Me_Again_Down_Here } from "next/font/google";
import "./globals.css";

// English font
const justMeAgainDownHere = Just_Me_Again_Down_Here({
  variable: "--font-just-me-again-down-here",
  subsets: ["latin"],
  weight: "400"
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${justMeAgainDownHere.variable} antialiased`}>{children}</body>
    </html>
  );
}
